# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: RMS CI

on:
  push:
    branches: [ deploy_ramsfrontend, dev_rmsfront ]
  pull_request:
    branches: [ deploy_ramsfrontend, dev_rmsfront ]

jobs:
  build:   
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      #installs Node Module to run the code
    - name: Install dependencies
      run: npm install
      #Builds the angular application using node and in production mode
    - name: Build
      run: npm run build -- --prod 
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2
      with:
        name: rmsFronEnd
